### ISSUE TITLE
It does not work on wayland!

### ISSUE THREAD

**Issue by RyanOrigens** [EmperorPenguin18/gobble#10] opened 2023-09-12 18:14 UTC
It doesn't hide the window.

TERMINAL OUTPUT:
warning: queue 0x7f7628000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@25 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@24 still attached
  wl_seat@23 still attached
  wl_data_device_manager@22 still attached
  wl_registry@20 still attached
warning: queue 0x55c7d92e96f0 destroyed while proxies still attached:
  xdg_wm_base@34 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by EmperorPenguin18** [comment] 2023-09-12 18:34
Duplicate of #2.

**Closed by EmperorPenguin18** 2023-09-12 18:34 UTC
